### ISSUE TITLE
Précision sur le champ hauteur_max

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/schema-stationnement#6]
Bonjour tout le monde,

Dans le cadre de la constitution de la base consolidée, nous avons des retours de producteurs. L'une des remarques est que certains parkings, même en enclos n'ont pas de limite de hauteur car le parking est en surface et la barrière ne limite pas la hauteur des véhicules. 
Pourrions-nous fixer une hauteur maximum par défaut (4m ?) ?

**Comment by geoffreyaldebert** [comment]
Hello @NicolasBerthelot La PR est passée #7 

On part donc sur le changement de type du champs hauteur_max de integer à string avec la possibilité de mettre la valeur "N/A" pour les cas où l'information n'est pas applicable.

@+

**Comment by NicolasBerthelot** [comment]
Top merci beaucoup Geoffrey !
